object Versions {
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.1"
    const val composeNavigation = "2.5.3"
    const val composeCompiler = "1.4.6"
    const val hilt = "2.38.1"
    const val hiltNavigationCompose = "1.0.0"
    const val okHttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val room = "2.5.0"
    const val timber = "5.0.1"
    const val coil = "2.2.2"
    const val coroutines = "1.3.9"
    const val leakcanary = "2.9.1"
    const val gson = "2.9.1"
    const val jUnitExt = "1.1.4"
    const val espressoCore = "3.5.0"
    const val lifecycle = "2.5.1"
    const val runtimeCompose = "2.6.0-beta01"
    const val javapoet="1.13.0"
}